import { useState } from 'react';
import { scoreBadgeTone } from '../lib/verdict/engine.js';

const TONE_CLASSES = {
  excellent: 'text-emerald-600 dark:text-emerald-400',
  good: 'text-emerald-600 dark:text-emerald-400',
  warning: 'text-amber-600 dark:text-amber-400',
  poor: 'text-red-600 dark:text-red-400',
};

/**
 * Preview surface — a single mechanism now for both generation modes:
 * `htmlDoc`, a self-contained HTML string rendered via iframe srcDoc.
 * Instant HTML mode builds this directly from plain files; Vite+React mode
 * builds it by bundling the project in-browser via esbuild-wasm (see
 * src/lib/bundler/clientBundle.js). Neither path calls out to a cloud
 * sandbox — there is no server-side build step for previewing anything.
 *
 * Also surfaces `verdictResult` — a local, zero-token design-QA score
 * (WCAG contrast, type-scale, spacing-grid, heading/landmark hierarchy)
 * computed inside the live preview itself and reported back via
 * postMessage. See src/lib/verdict/.
 */
export default function PreviewPane({ htmlDoc, bundling, bundleErrors, selectedFile, healStatus, verdictResult, runtimeQaResult, generationSource }) {
  const [tab, setTab] = useState('preview');

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center justify-between border-b border-neutral-200 px-3 py-1.5 dark:border-neutral-800">
        <div className="flex gap-1">
          {['preview', 'code'].map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={
                'rounded-md px-3 py-1 text-xs font-medium capitalize ' +
                (tab === t ? 'bg-neutral-200 dark:bg-neutral-800' : 'text-neutral-500 hover:bg-neutral-100 dark:hover:bg-neutral-800')
              }
            >
              {t}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-3">
          {generationSource === 'local' && (
            <span className="text-xs font-medium text-indigo-600 dark:text-indigo-400" title="Generated by an on-device model running in your browser — no API key, no cloud call">
              On-device model
            </span>
          )}
          {verdictResult && (
            <span
              className={'text-xs font-medium ' + (TONE_CLASSES[scoreBadgeTone(verdictResult.score)] || '')}
              title={`${verdictResult.issues.length} issue(s) across contrast, type scale, spacing grid, and heading/landmark hierarchy`}
            >
              Verdict: {verdictResult.score}/100
            </span>
          )}
          {runtimeQaResult && (
            <span
              className={'text-xs font-medium ' + (runtimeQaResult.brokenCount === 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400')}
              title={`Clicked ${runtimeQaResult.testedCount} interactive element(s) in the live preview; ${runtimeQaResult.brokenCount} threw an error. Forms are never actually submitted (safety).`}
            >
              Runtime QA: {runtimeQaResult.brokenCount === 0 ? `${runtimeQaResult.testedCount}/${runtimeQaResult.testedCount} OK` : `${runtimeQaResult.brokenCount} broken`}
            </span>
          )}
          {htmlDoc && <span className="text-xs text-emerald-600 dark:text-emerald-400">In-browser preview — no cloud sandbox</span>}
          {bundling && <span className="text-xs text-neutral-400 dark:text-neutral-500">Bundling in your browser…</span>}
          {!bundling && healStatus && (
            <span className={'text-xs ' + (healStatus.ok ? 'text-emerald-600 dark:text-emerald-400' : 'text-amber-600 dark:text-amber-400')}>
              {healStatus.ok
                ? healStatus.healed
                  ? `Self-healed after ${healStatus.attempts} attempt(s)`
                  : 'Built clean'
                : `Attempt ${healStatus.attempts}/3 — fixing build errors…`}
            </span>
          )}
        </div>
      </div>

      <div className="flex-1 overflow-hidden bg-neutral-50 dark:bg-neutral-950">
        {tab === 'preview' ? (
          htmlDoc ? (
            <iframe title="Live preview" srcDoc={htmlDoc} sandbox="allow-scripts allow-forms allow-popups allow-modals" className="h-full w-full border-0" />
          ) : bundleErrors?.length ? (
            <pre className="h-full overflow-auto p-4 text-xs text-red-600 dark:text-red-400">{bundleErrors.join('\n')}</pre>
          ) : (
            <div className="flex h-full items-center justify-center text-sm text-neutral-400 dark:text-neutral-500">
              No preview running yet.
            </div>
          )
        ) : (
          <pre className="h-full overflow-auto p-4 text-xs">
            <code>{selectedFile?.content || 'Select a file from the explorer.'}</code>
          </pre>
        )}
      </div>
    </div>
  );
}
